apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app-example
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/jecklgamis
    chart: fastapi-app-example
    targetRevision: 1.0.0-rc.1
    helm:
      values: |
        image:
          tag: main
        ingress:
          hosts:
            - host: fastapi-app-example.jecklgamis.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: fastapi-app-example
              hosts:
                - fastapi-app-example.jecklgamis.com
        imagePullSecrets:
          - name: dockerhub
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-app-example
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
